services:
  api:
    build: ./backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - target: 8000
        published: ${API_PORT}
        protocol: tcp
    env_file:
      - ./backend/.env

  client:
    depends_on:
      - api
    build: ./frontend
    command: npm run start
    volumes:
      - ./frontend:/app
    ports:
      - target: 3000
        published: ${CLIENT_PORT}
        protocol: tcp
    env_file:
      - ./frontend/.env
