[tool.ruff]
show-fixes = true
target-version = "py311"

[tool.ruff.lint]
extend-select = ["ANN", "C4", "COM", "I", "N", "PT", "RET", "SIM", "TCH", "TID"]
ignore = ["ANN003", "ANN101", "ANN102", "ANN201", "ANN202", "COM812"]

[tool.ruff.lint.isort]
case-sensitive = true

[tool.mypy]
python_version = "3.11"
mypy_path = "backend"
