[tool.ruff]
extend-select = ["ANN", "C4", "COM", "I", "N", "PT", "RET", "SIM", "TCH", "TID"]
ignore = ["ANN101", "ANN102"]
show-fixes = true
line-length = 120

[tool.ruff.isort]
case-sensitive = true

