services:
  api:
    build:
      context: ../backend/
      target: development
    volumes:
      - ../backend/:/home/app/
      - /app/.venv
    ports:
      - "8000:8000"
    env_file:
      - ../.env

  client:
    depends_on:
      - api
    build: ../frontend/
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"
      # - target: 5173
      #   published: ${CLIENT_PORT}
      #   protocol: tcp
    env_file:
      - ../frontend/.env
